<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasGewogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('
        INSERT INTO `mas_gewogs` (`mas_dzongkhag_id`, `name`, `created_by`) VALUES
        (1, "Chhoekhor", 1),
        (1, "Chhume", 1),
        (1, "Tang", 1),
        (1, "Ura", 1),

        (2, "Bjachho", 1),
        (2, "Bongo", 1),
        (2, "Chapcha", 1),
        (2, "Darla", 1),
        (2, "Dungna", 1),
        (2, "Geling", 1),
        (2, "Getana", 1),
        (2, "Lokchina", 1),
        (2, "Metakha", 1),
        (2, "Phuentsholing", 1),
        (2, "Sampheling", 1),

        (3, "Dorona", 1),
        (3, "Drujegang", 1),
        (3, "Gesarling", 1),
        (3, "Goshi", 1),
        (3, "Kana", 1),
        (3, "Karmaling", 1),
        (3, "Khebisa", 1),
        (3, "Lajab", 1),
        (3, "Lhamoi Zingkha", 1),
        (3, "Nichula", 1),
        (3, "Trashiding", 1),
        (3, "Tsangkha", 1),
        (3, "Tsendagang", 1),
        (3, "Tseza", 1),

        (4, "Khamaed", 1),
        (4, "Khatoe", 1),
        (4, "Laya", 1),
        (4, "Lunana", 1),

        (5, "Bji", 1),
        (5, "Gakiling", 1),
        (5, "Katsho", 1),
        (5, "Samar", 1),
        (5, "Sangbay", 1),
        (5, "Uesu", 1),

        (6, "Gangzur", 1),
        (6, "Khoma", 1),
        (6, "Jarey", 1),
        (6, "Kurtoed", 1),
        (6, "Menbi", 1),
        (6, "Metsho", 1),
        (6, "Minjay", 1),
        (6, "Tsenkhar", 1),

        (7, "Balam", 1),
        (7, "Chali", 1),
        (7, "Chaskhar", 1),
        (7, "Drametse", 1),
        (7, "Drepong", 1),
        (7, "Gongdue", 1),
        (7, "Jurmey", 1),
        (7, "Kengkhar", 1),
        (7, "Mongar", 1),
        (7, "Narang", 1),
        (7, "Ngatshang", 1),
        (7, "Saling", 1),
        (7, "Shermuhoong", 1),
        (7, "Silambi", 1),
        (7, "Thangrong", 1),
        (7, "Tsakaling", 1),
        (7, "Tsamang", 1),

        (8, "Dokar", 1),
        (8, "Dopshari", 1),
        (8, "Doteng", 1),
        (8, "Hungrel", 1),
        (8, "Lamgong", 1),
        (8, "Lungnyi", 1),
        (8, "Naja", 1),
        (8, "Shapa", 1),
        (8, "Tsento", 1),
        (8, "Wangchang", 1),

        (9, "Chimoong", 1),
        (9, "Chokhorling", 1),
        (9, "Chongshing", 1),
        (9, "Dechheling", 1),
        (9, "Dungmaed", 1),
        (9, "Khar", 1),
        (9, "Nanong", 1),
        (9, "Norbugang", 1),
        (9, "Shumar", 1),
        (9, "Yurung", 1),
        (9, "Zobel", 1),

        (10, "Barp", 1),
        (10, "Chhubug", 1),
        (10, "Dzomi", 1),
        (10, "Goenshari", 1),
        (10, "Guma", 1),
        (10, "Kabisa", 1),
        (10, "Lingmukha", 1),
        (10, "Shenga Bjemi", 1),
        (10, "Talog", 1),
        (10, "Toepisa", 1),
        (10, "Toewang", 1),

        (11, "Dewathang", 1),
        (11, "Gomdar", 1),
        (11, "Langchenphu", 1),
        (11, "Lauri", 1),
        (11, "Martshala", 1),
        (11, "Orong", 1),
        (11, "Pemathang", 1),
        (11, "Phuntshothang", 1),
        (11, "Samrang", 1),
        (11, "Serthi", 1),
        (11, "Wangphu", 1),
        
        (12, "Dungtoe", 1),
        (12, "Dophoogchen", 1),
        (12, "Duenchukha", 1),
        (12, "Namgaychhoeling", 1),
        (12, "Norbugang", 1),
        (12, "Norgaygang", 1),
        (12, "Pemaling", 1),
        (12, "Phuentshogpelri", 1),
        (12, "Samtse", 1),
        (12, "Sangngagchhoeling", 1),
        (12, "Tading", 1),
        (12, "Tashicholing", 1),
        (12, "Tendruk", 1),
        (12, "Ugentse", 1),
        (12, "Yoeseltse", 1),

        (13, "Chhuzagang", 1),
        (13, "Chhudzom", 1),
        (13, "Dekiling", 1),
        (13, "Gakiling", 1),
        (13, "Gelephu", 1),
        (13, "Jigmechholing", 1),
        (13, "Samtenling", 1),
        (13, "Senggey", 1),
        (13, "Sherzhong", 1),
        (13, "Shompangkha", 1),
        (13, "Tareythang", 1),
        (13, "Umling", 1),

        (14, "Chang", 1),
        (14, "Darkala", 1),
        (14, "Genye", 1),
        (14, "Kawang", 1),
        (14, "Lingzhi", 1),
        (14, "Mewang", 1),
        (14, "Naro", 1),
        (14, "Soe", 1),

        (15, "Bartsham", 1),
        (15, "Bidung", 1),
        (15, "Kanglung", 1),
        (15, "Kangpar", 1),
        (15, "Khaling", 1),
        (15, "Lumang", 1),
        (15, "Merag", 1),
        (15, "Phongmed", 1),
        (15, "Radi", 1),
        (15, "Sagteng", 1),
        (15, "Samkhar", 1),
        (15, "Shongphoog", 1),
        (15, "Thrimshing", 1),
        (15, "Uzorong", 1),
        (15, "Yangnyer", 1),

        (16, "Bumdeling", 1),
        (16, "Jamkhar", 1),
        (16, "Khamdang", 1),
        (16, "Ramjar", 1),
        (16, "Toetsho", 1),
        (16, "Tomzhang", 1),
        (16, "Yalang", 1),
        (16, "Yangtse", 1),

        (17, "Dragteng", 1),
        (17, "Korphoog", 1),
        (17, "Langthil", 1),
        (17, "Nubi", 1),
        (17, "Tangsibji", 1),

        (18, "Barshong", 1),
        (18, "Dunglegang", 1),
        (18, "Gosarling", 1),
        (18, "Kikhorthang", 1),
        (18, "Mendrelgang", 1),
        (18, "Patshaling", 1),
        (18, "Phuntenchu", 1),
        (18, "Rangthangling", 1),
        (18, "Semjong", 1),
        (18, "Sergithang", 1),
        (18, "Tsholingkhar", 1),
        (18, "Tsirangtoe", 1),

        (19, "Athang", 1),
        (19, "Bjendag", 1),
        (19, "Darkar", 1),
        (19, "Dangchu", 1),
        (19, "Gangteng", 1),
        (19, "Gasetsho Gom", 1),
        (19, "Gasetsho Wom", 1),
        (19, "Kazhi", 1),
        (19, "Nahi", 1),
        (19, "Nyisho", 1),
        (19, "Phangyul", 1),
        (19, "Phobji", 1),
        (19, "Ruepisa", 1),
        (19, "Sephu", 1),
        (19, "Thedtsho", 1),

        (20, "Bardo", 1),
        (20, "Bjoka", 1),
        (20, "Goshing", 1),
        (20, "Nangkor", 1),
        (20, "Ngangla", 1),
        (20, "Phangkhar", 1),
        (20, "Shingkhar", 1),
        (20, "Trong", 1)
    ');
    }
}
