<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasPayHeadsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement("
            INSERT INTO mas_pay_heads (
                name,
                code,
                general_ledger_code,
                payhead_type,
                calculation_method,
                calculated_on,
                amount,
                mas_pay_slab_id,
                mas_pay_group_id,
                account_head_id,
                formula,
                created_by,
                updated_by,
                created_at,
                updated_at
            )
            VALUES
                (
                    'Medical Allowance',
                    'Medical ALL',
                    '52711',
                    1,
                    2,
                    1,
                    12.00,
                    1,
                    NULL,
                    1,
                    NULL,
                    1,
                    NULL,
                    '2024-08-20 08:11:10',
                    '2024-08-20 08:11:10'
                ),
                (
                    'Project Allowance',
                    'Project ALL',
                    '52336',
                    1,
                    6,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    1,
                    NULL,
                    1,
                    1,
                    '2024-08-20 08:11:10',
                    '2024-09-17 17:10:02'
                ),
                (
                    'Critical Allowance',
                    'Critical ALL',
                    '52337',
                    1,
                    4,
                    6,
                    NULL,
                    1,
                    3,
                    1,
                    NULL,
                    1,
                    1,
                    '2024-08-20 08:11:10',
                    '2024-09-19 09:33:12'
                ),
                (
                    'Overtime Allowance',
                    'Overtime ALL',
                    'ot1001',
                    1,
                    6,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    1,
                    'THEN [OVERTIME_HOURS] * [HOURLY_WAGE]',
                    1,
                    NULL,
                    '2024-08-20 08:11:10',
                    '2024-08-20 08:11:10'
                ),
                (
                    'Corporate Allowance',
                    'Corporate ALL',
                    'Corporate1001',
                    1,
                    4,
                    6,
                    NULL,
                    NULL,
                    4,
                    1,
                    NULL,
                    1,
                    NULL,
                    NULL,
                    NULL
                );
        ");

        DB::statement("
            INSERT INTO mas_pay_heads (
                name,
                code,
                general_ledger_code,
                payhead_type,
                calculation_method,
                calculated_on,
                amount,
                mas_pay_slab_id,
                mas_pay_group_id,
                account_head_id,
                formula,
                created_by,
                updated_by,
                created_at,
                updated_at
            )
            VALUES
                (
                    'Salary Tax',
                    'TDS',
                    '23173',
                    2,
                    3,
                    4,
                    NULL,
                    1,
                    NULL,
                    2,
                    NULL,
                    1,
                    NULL,
                    '2024-08-20 08:11:10',
                    '2024-08-20 08:11:10'
                ),
                (
                    'Health Tax',
                    'H/Tax',
                    '23183',
                    2,
                    6,
                    NULL,
                    NULL,
                    NULL,
                    NULL,
                    2,
                    'IF ([EMPLOYMENT_TYPE] == 1 OR [EMPLOYMENT_TYPE] == 3) THEN ([GROSS_PAY] * 0.01) ELSE THEN 0 ENDIF',
                    1,
                    1,
                    '2024-08-20 08:11:10',
                    '2024-09-20 15:32:02'
                ),
                (
                    'Provident Fund',
                    'PF',
                    '23181',
                    2,
                    6,
                    NULL,
                    NULL,
                    1,
                    1,
                    2,
                    'IF ([EMPLOYMENT_TYPE] == 1) THEN ([BASIC_PAY] * 0.15) ELSEIF ([EMPLOYMENT_TYPE] == 3) THEN ([BASIC_PAY] * 0.15) ELSEIF ([EMPLOYMENT_TYPE] == 4 OR [EMPLOYMENT_TYPE] == 5) THEN ([BASIC_PAY] * 0.05) ELSE THEN 0 ENDIF',
                    1,
                    1,
                    '2024-08-20 08:11:10',
                    '2024-09-17 18:05:53'
                ),
                (
                    'Staff Initiative for Financial Assistance',
                    'SIFA',
                    '23203',
                    2,
                    4,
                    1,
                    NULL,
                    NULL,
                    1,
                    2,
                    NULL,
                    1,
                    NULL,
                    '2024-08-20 08:11:10',
                    '2024-08-20 08:11:10'
                ),
                (
                    'Group Savings Linked Insurance',
                    'GSLI',
                    '23192',
                    2,
                    3,
                    1,
                    NULL,
                    2,
                    NULL,
                    2,
                    NULL,
                    1,
                    NULL,
                    '2024-08-20 08:11:10',
                    '2024-08-20 08:11:10'
                ),
                (
                    'Device EMI',
                    'Device EMI',
                    '',
                    2,
                    7,
                    0,
                    NULL,
                    NULL,
                    NULL,
                    2,
                    NULL,
                    1,
                    NULL,
                    '2024-08-20 08:11:10',
                    '2024-08-20 08:11:10'
                ),
                (
                    'Loan BOB',
                    'Loan BOB',
                    '23193',
                    2,
                    7,
                    1,
                    NULL,
                    1,
                    1,
                    2,
                    NULL,
                    1,
                    1,
                    NULL,
                    '2024-09-20 14:09:08'
                ),
                (
                    'Loan BNB',
                    'Loan BNB',
                    '23194',
                    2,
                    7,
                    1,
                    NULL,
                    1,
                    1,
                    2,
                    NULL,
                    1,
                    1,
                    NULL,
                    '2024-09-20 14:09:08'
                ),
                (
                    'Loan RICB',
                    'Loan RICB',
                    '23209',
                    2,
                    7,
                    1,
                    NULL,
                    1,
                    1,
                    2,
                    NULL,
                    1,
                    1,
                    NULL,
                    '2024-09-20 14:09:08'
                ),
                (
                    'Loan BDFC',
                    'Loan BDFC',
                    '23189',
                    2,
                    7,
                    1,
                    NULL,
                    1,
                    1,
                    2,
                    NULL,
                    1,
                    1,
                    NULL,
                    '2024-09-20 14:09:08'
                ),
                (
                    'Loan DPNB',
                    'Loan DPNB',
                    '23196',
                    2,
                    7,
                    1,
                    NULL,
                    1,
                    1,
                    2,
                    NULL,
                    1,
                    1,
                    NULL,
                    '2024-09-20 14:09:08'
                ),
                (
                    'Loan NPPF',
                    'Loan NPPF',
                    '23198',
                    2,
                    7,
                    1,
                    NULL,
                    1,
                    1,
                    2,
                    NULL,
                    1,
                    1,
                    NULL,
                    '2024-09-20 14:09:08'
                ),
                (
                    'Loan SIFA',
                    'Loan SIFA',
                    '23198',
                    2,
                    7,
                    1,
                    NULL,
                    1,
                    1,
                    2,
                    NULL,
                    1,
                    1,
                    NULL,
                    '2024-09-20 14:09:08'
                ),
                (
                    'Loan TBank',
                    'Loan TBank',
                    '23190',
                    2,
                    7,
                    1,
                    NULL,
                    1,
                    1,
                    2,
                    NULL,
                    1,
                    1,
                    NULL,
                    '2024-09-20 14:11:44'
                );
        ");

    }
}
