<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasVillagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('mas_villages')->insert([
            ['id' => 1, 'village' => 'Damphel', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 2, 'village' => 'Dodrong', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 3, 'village' => 'Kangdok', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 4, 'village' => 'Nang Lhakang', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 5, 'village' => 'Samthang', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 6, 'village' => 'Saram', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 7, 'village' => 'Tashiling (Chokhor)', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 8, 'village' => 'Tendok', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 9, 'village' => 'Zangling', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 10, 'village' => 'Zhabjethang', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 11, 'village' => 'Druk Dok', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 12, 'village' => 'Dhur Lusibee', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 13, 'village' => 'Dhur Moen', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 14, 'village' => 'Goling', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 15, 'village' => 'Kharsa', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 16, 'village' => 'Shukdak', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 17, 'village' => 'Thangbi', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 18, 'village' => 'Chakhar', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 19, 'village' => 'Changwa', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 20, 'village' => 'Dawathang', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 21, 'village' => 'Dorjibe', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 22, 'village' => 'Jamphel Lhakhang', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 23, 'village' => 'Norbugang', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 24, 'village' => 'Pangrey', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 25, 'village' => 'Potola', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 26, 'village' => 'Kenchosum', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 27, 'village' => 'Kharsum', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 28, 'village' => 'Pedtsheling', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 29, 'village' => 'Tamshing', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 30, 'village' => 'Torshong', 'mas_gewog_id' => 1, 'created_by' => 1],
            ['id' => 31, 'village' => 'Buli', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 32, 'village' => 'Buli/Uru', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 33, 'village' => 'Choda', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 34, 'village' => 'Gyaltsa', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 35, 'village' => 'Samtenling', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 36, 'village' => 'Uru', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 37, 'village' => 'Urudrangbi', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 38, 'village' => 'Domkhar', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 39, 'village' => 'Zincha', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 40, 'village' => 'Chedeypang', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 41, 'village' => 'Phurjoen', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 42, 'village' => 'Thrometh', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 43, 'village' => 'Ursang', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 44, 'village' => 'Pangteygoenpa', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 45, 'village' => 'Yamthrag', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 46, 'village' => 'Nangar', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 47, 'village' => 'Trakar', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 48, 'village' => 'Thrometh (Samling)', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 49, 'village' => 'Zugney', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 50, 'village' => 'Zugney (Chorten Nengpa)', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 51, 'village' => 'Bhim', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 52, 'village' => 'Choongphel', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 53, 'village' => 'Terzok', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 54, 'village' => 'Tharpaling', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 55, 'village' => 'Yerangbi', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 56, 'village' => 'Zhurey', 'mas_gewog_id' => 2, 'created_by' => 1],
            ['id' => 57, 'village' => 'Tandigang', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 58, 'village' => 'Benzabi', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 59, 'village' => 'Chhutoe', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 60, 'village' => 'Gambling', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 61, 'village' => 'Khangrab', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 62, 'village' => 'Khoyar', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 63, 'village' => 'Namkha', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 64, 'village' => 'Shobugoenpa', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 65, 'village' => 'Tashiling (Tang)', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 66, 'village' => 'Ugyenchholing', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 67, 'village' => 'Chojam', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 68, 'village' => 'Gangju', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 69, 'village' => 'Kidzom', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 70, 'village' => 'Nangnang', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 71, 'village' => 'Nimalung', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 72, 'village' => 'Tralang', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 73, 'village' => 'Sameth', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 74, 'village' => 'Dazur', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 75, 'village' => 'Jamshong', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 76, 'village' => 'Jog', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 77, 'village' => 'Misserthang', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 78, 'village' => 'Pangshing', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 79, 'village' => 'Rimochen', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 80, 'village' => 'Bezur', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 81, 'village' => 'Kuenzangdrang', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 82, 'village' => 'Phom Drong', 'mas_gewog_id' => 3, 'created_by' => 1],
            ['id' => 83, 'village' => 'Beteng', 'mas_gewog_id' => 4, 'created_by' => 1],
            ['id' => 84, 'village' => 'Pangkhar', 'mas_gewog_id' => 4, 'created_by' => 1],
            ['id' => 85, 'village' => 'Soomthrang', 'mas_gewog_id' => 4, 'created_by' => 1],
            ['id' => 86, 'village' => 'Tansibi', 'mas_gewog_id' => 4, 'created_by' => 1],
            ['id' => 87, 'village' => 'Sing-nyer', 'mas_gewog_id' => 4, 'created_by' => 1],
            ['id' => 88, 'village' => 'Ura-Charipa', 'mas_gewog_id' => 4, 'created_by' => 1],
            ['id' => 89, 'village' => 'Ura-Tarshong', 'mas_gewog_id' => 4, 'created_by' => 1],
            ['id' => 90, 'village' => 'Ura-Toepda', 'mas_gewog_id' => 4, 'created_by' => 1],
            ['id' => 91, 'village' => 'Ura-Trab Krispai', 'mas_gewog_id' => 4, 'created_by' => 1],
            ['id' => 92, 'village' => 'Shingkhar', 'mas_gewog_id' => 4, 'created_by' => 1],
            ['id' => 93, 'village' => 'Bjagchhog', 'mas_gewog_id' => 5, 'created_by' => 1],
            ['id' => 94, 'village' => 'Tsimakha', 'mas_gewog_id' => 5, 'created_by' => 1],
            ['id' => 95, 'village' => 'Tsimasham', 'mas_gewog_id' => 5, 'created_by' => 1],
            ['id' => 96, 'village' => 'Mebisa', 'mas_gewog_id' => 5, 'created_by' => 1],
            ['id' => 97, 'village' => 'Tashi Gatshel', 'mas_gewog_id' => 5, 'created_by' => 1],
            ['id' => 98, 'village' => 'Wangkha', 'mas_gewog_id' => 5, 'created_by' => 1],
            ['id' => 99, 'village' => 'Togtokha', 'mas_gewog_id' => 6, 'created_by' => 1],
            ['id' => 100, 'village' => 'Choongkha', 'mas_gewog_id' => 6, 'created_by' => 1],
            ['id' => 101, 'village' => 'Chhasilakha', 'mas_gewog_id' => 6, 'created_by' => 1],
            ['id' => 102, 'village' => 'Gedu', 'mas_gewog_id' => 6, 'created_by' => 1],
            ['id' => 103, 'village' => 'Jurma', 'mas_gewog_id' => 6, 'created_by' => 1],
            ['id' => 104, 'village' => 'Boeri', 'mas_gewog_id' => 6, 'created_by' => 1],
            ['id' => 105, 'village' => 'Miritsemo', 'mas_gewog_id' => 6, 'created_by' => 1],
            ['id' => 106, 'village' => 'Pakshikha', 'mas_gewog_id' => 6, 'created_by' => 1],
            ['id' => 107, 'village' => 'Damji', 'mas_gewog_id' => 6, 'created_by' => 1],
            ['id' => 108, 'village' => 'Ketogkha', 'mas_gewog_id' => 6, 'created_by' => 1],
            ['id' => 109, 'village' => 'Bongo', 'mas_gewog_id' => 6, 'created_by' => 1],
            ['id' => 110, 'village' => 'Junglay', 'mas_gewog_id' => 6, 'created_by' => 1],
            ['id' => 111, 'village' => 'Phashooma', 'mas_gewog_id' => 6, 'created_by' => 1],
            ['id' => 112, 'village' => 'Zamsa', 'mas_gewog_id' => 6, 'created_by' => 1],
            ['id' => 113, 'village' => 'Baeyuel Kunzang', 'mas_gewog_id' => 6, 'created_by' => 1],
            ['id' => 114, 'village' => 'Pagga', 'mas_gewog_id' => 7, 'created_by' => 1],
            ['id' => 115, 'village' => 'Pagga Goenpa', 'mas_gewog_id' => 7, 'created_by' => 1],
            ['id' => 116, 'village' => 'Jongzhi', 'mas_gewog_id' => 7, 'created_by' => 1],
            ['id' => 117, 'village' => 'Metep', 'mas_gewog_id' => 7, 'created_by' => 1],
            ['id' => 118, 'village' => 'Tsamdrag', 'mas_gewog_id' => 7, 'created_by' => 1],
            ['id' => 119, 'village' => 'Gangkha', 'mas_gewog_id' => 7, 'created_by' => 1],
            ['id' => 120, 'village' => 'Shelgoan', 'mas_gewog_id' => 7, 'created_by' => 1],
            ['id' => 121, 'village' => 'Sheyuel', 'mas_gewog_id' => 7, 'created_by' => 1],
            ['id' => 122, 'village' => 'Dorgoen', 'mas_gewog_id' => 7, 'created_by' => 1],
            ['id' => 123, 'village' => 'Rimtekha', 'mas_gewog_id' => 7, 'created_by' => 1],
            ['id' => 124, 'village' => 'Lang Nyelsa', 'mas_gewog_id' => 7, 'created_by' => 1],
            ['id' => 125, 'village' => 'Bunakha', 'mas_gewog_id' => 7, 'created_by' => 1],
            ['id' => 126, 'village' => 'Dangreyboog (Bich Darla)', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 127, 'village' => 'Tagp-thang-boog (Bich Saureni)', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 128, 'village' => 'Khamaedthapang (Lower Saureni)', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 129, 'village' => 'Norgangtoed', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 130, 'village' => 'Nyimgang (Ghamdara)', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 131, 'village' => 'Tabji', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 132, 'village' => 'Rinchhentse (Gurung Goan)', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 133, 'village' => 'Chhumedlakha (Barkhey)', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 134, 'village' => 'Gengu', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 135, 'village' => 'Yagang', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 136, 'village' => 'Pagshinggang (Pakshina)', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 137, 'village' => 'Samarchen (Samachin)', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 138, 'village' => 'Sillangsa (Silley)', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 139, 'village' => 'Sinchula', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 140, 'village' => 'Dojangchhey (Dojangchey)', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 141, 'village' => 'Kimalakha', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 142, 'village' => 'Gamanang', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 143, 'village' => 'Sharphug (Sangkhu)', 'mas_gewog_id' => 8, 'created_by' => 1],
            ['id' => 144, 'village' => 'Papaling', 'mas_gewog_id' => 9, 'created_by' => 1],
            ['id' => 145, 'village' => 'Babana', 'mas_gewog_id' => 9, 'created_by' => 1],
            ['id' => 146, 'village' => 'Mangdokha', 'mas_gewog_id' => 9, 'created_by' => 1],
            ['id' => 147, 'village' => 'Doongma', 'mas_gewog_id' => 9, 'created_by' => 1],
            ['id' => 148, 'village' => 'Pangu', 'mas_gewog_id' => 9, 'created_by' => 1],
            ['id' => 149, 'village' => 'Drukdingsa', 'mas_gewog_id' => 9, 'created_by' => 1],
            ['id' => 150, 'village' => 'Uezhi', 'mas_gewog_id' => 9, 'created_by' => 1],
            ['id' => 151, 'village' => 'Tsanglina', 'mas_gewog_id' => 10, 'created_by' => 1],
            ['id' => 152, 'village' => 'Dagpa', 'mas_gewog_id' => 10, 'created_by' => 1],
            ['id' => 153, 'village' => 'Changeykha', 'mas_gewog_id' => 10, 'created_by' => 1],
            ['id' => 154, 'village' => 'Omchhu', 'mas_gewog_id' => 10, 'created_by' => 1],
            ['id' => 155, 'village' => 'Geygoen', 'mas_gewog_id' => 10, 'created_by' => 1],
            ['id' => 156, 'village' => 'Nayekha', 'mas_gewog_id' => 10, 'created_by' => 1],
            ['id' => 157, 'village' => 'Dilib', 'mas_gewog_id' => 10, 'created_by' => 1],
            ['id' => 158, 'village' => 'Daga', 'mas_gewog_id' => 11, 'created_by' => 1],
            ['id' => 159, 'village' => 'Tshebji', 'mas_gewog_id' => 11, 'created_by' => 1],
            ['id' => 160, 'village' => 'Trashigang', 'mas_gewog_id' => 11, 'created_by' => 1],
            ['id' => 161, 'village' => 'Phootsha', 'mas_gewog_id' => 11, 'created_by' => 1],
            ['id' => 162, 'village' => 'Bachhu', 'mas_gewog_id' => 11, 'created_by' => 1],
            ['id' => 163, 'village' => 'Chiyuel', 'mas_gewog_id' => 11, 'created_by' => 1],
            ['id' => 164, 'village' => 'Pangsela', 'mas_gewog_id' => 11, 'created_by' => 1],
            ['id' => 165, 'village' => 'Chagdokha (Chadokha)', 'mas_gewog_id' => 12, 'created_by' => 1],
            ['id' => 166, 'village' => 'Damchekha', 'mas_gewog_id' => 12, 'created_by' => 1],
            ['id' => 167, 'village' => 'Lotokha', 'mas_gewog_id' => 12, 'created_by' => 1],
            ['id' => 168, 'village' => 'Bjagchhu', 'mas_gewog_id' => 12, 'created_by' => 1],
            ['id' => 169, 'village' => 'Dolepchen', 'mas_gewog_id' => 12, 'created_by' => 1],
            ['id' => 170, 'village' => 'Dofam', 'mas_gewog_id' => 12, 'created_by' => 1],
            ['id' => 171, 'village' => 'Aamleg', 'mas_gewog_id' => 12, 'created_by' => 1],
            ['id' => 172, 'village' => 'Pamji', 'mas_gewog_id' => 12, 'created_by' => 1],
            ['id' => 173, 'village' => 'Dupanang (Dubeni)', 'mas_gewog_id' => 12, 'created_by' => 1],
            ['id' => 174, 'village' => 'Dzedokha', 'mas_gewog_id' => 12, 'created_by' => 1],
            ['id' => 175, 'village' => 'Chimongna Ka (Chimuna A)', 'mas_gewog_id' => 12, 'created_by' => 1],
            ['id' => 176, 'village' => 'Chimongna Kha (Chimuna B)', 'mas_gewog_id' => 12, 'created_by' => 1],
            ['id' => 177, 'village' => 'Pangu', 'mas_gewog_id' => 13, 'created_by' => 1],
            ['id' => 178, 'village' => 'Metap Goenpa Toed', 'mas_gewog_id' => 13, 'created_by' => 1],
            ['id' => 179, 'village' => 'Metap Goenpa Maed', 'mas_gewog_id' => 13, 'created_by' => 1],
            ['id' => 180, 'village' => 'Uekha', 'mas_gewog_id' => 13, 'created_by' => 1],
            ['id' => 181, 'village' => 'Gumina', 'mas_gewog_id' => 13, 'created_by' => 1],
            ['id' => 182, 'village' => 'Bosokha', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 183, 'village' => 'Gangteng (Serina)', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 184, 'village' => 'Lingdaen', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 185, 'village' => 'Tashidingkha', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 186, 'village' => 'Dajaygang', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 187, 'village' => 'Pachhuthang (Balden Dara)', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 188, 'village' => 'Pachhudrag (Pachu Dara)', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 189, 'village' => 'Pachhugang (Pachu Tar)', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 190, 'village' => 'Toribari', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 191, 'village' => 'Ahalay (Dophugchen)', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 192, 'village' => 'Wangdue Gatshel (Ramitay)', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 193, 'village' => 'Marpji (Chilauney)', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 194, 'village' => 'Deling (Chomchey)', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 195, 'village' => 'Chongeykha A', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 196, 'village' => 'Chonggeykha B', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 197, 'village' => 'Dophulakha', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 198, 'village' => 'Kungkha', 'mas_gewog_id' => 14, 'created_by' => 1],
            ['id' => 199, 'village' => 'Rigzinling (Behitar)', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 200, 'village' => 'Pekarling (Pekasey)', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 201, 'village' => 'Tshachhungnal (Ahalay)', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 202, 'village' => 'Khatob (Burkey)', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 203, 'village' => 'Dungkarling (Ghumauney)', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 204, 'village' => 'Phurpaling', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 205, 'village' => 'Gurung Dara', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 206, 'village' => 'Karmaling (Malbasay)', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 207, 'village' => 'Sengyegang(Singi)', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 208, 'village' => 'Thongling (Daragoan)', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 209, 'village' => 'Khepaithang (Khaibatar)', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 210, 'village' => 'Sonamtang (Kothiline)', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 211, 'village' => 'Pangna A', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 212, 'village' => 'Pangna B', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 213, 'village' => 'Pangna C', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 214, 'village' => 'Bamenmo (Ragaythung)', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 215, 'village' => 'Doruphug (Dhungayna)', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 216, 'village' => 'Pedtshelnang (Pakchina)', 'mas_gewog_id' => 15, 'created_by' => 1],
            ['id' => 217, 'village' => 'Chukam', 'mas_gewog_id' => 16, 'created_by' => 1],
            ['id' => 218, 'village' => 'Lalidhapper', 'mas_gewog_id' => 16, 'created_by' => 1],
            ['id' => 219, 'village' => 'Maamedthang', 'mas_gewog_id' => 16, 'created_by' => 1],
            ['id' => 220, 'village' => 'Banglachu', 'mas_gewog_id' => 16, 'created_by' => 1],
            ['id' => 221, 'village' => 'Nyimtola', 'mas_gewog_id' => 16, 'created_by' => 1],
            ['id' => 222, 'village' => 'Dorona Chhoongwa (Sanu Dorona)', 'mas_gewog_id' => 16, 'created_by' => 1],
            ['id' => 223, 'village' => 'Dorona Chhewa (Thulo Dorona)', 'mas_gewog_id' => 16, 'created_by' => 1],
            ['id' => 224, 'village' => 'Dolepchen', 'mas_gewog_id' => 16, 'created_by' => 1],
            ['id' => 225, 'village' => 'Nedachu', 'mas_gewog_id' => 16, 'created_by' => 1],
            ['id' => 226, 'village' => 'Sushithang', 'mas_gewog_id' => 16, 'created_by' => 1],
            ['id' => 227, 'village' => 'Upper Pangna', 'mas_gewog_id' => 17, 'created_by' => 1],
            ['id' => 228, 'village' => 'Tangna', 'mas_gewog_id' => 17, 'created_by' => 1],
            ['id' => 229, 'village' => 'Lower Pangna', 'mas_gewog_id' => 17, 'created_by' => 1],
            ['id' => 230, 'village' => 'Lower Pangserbo', 'mas_gewog_id' => 17, 'created_by' => 1],
            ['id' => 231, 'village' => 'Upper Pangserbo', 'mas_gewog_id' => 17, 'created_by' => 1],
            ['id' => 232, 'village' => 'Tajoog', 'mas_gewog_id' => 18, 'created_by' => 1],
            ['id' => 233, 'village' => 'Samtengang', 'mas_gewog_id' => 18, 'created_by' => 1],
            ['id' => 234, 'village' => 'Gangjab', 'mas_gewog_id' => 18, 'created_by' => 1],
            ['id' => 235, 'village' => 'Gesarling', 'mas_gewog_id' => 18, 'created_by' => 1],
            ['id' => 236, 'village' => 'Phuensoomgang', 'mas_gewog_id' => 18, 'created_by' => 1],
            ['id' => 237, 'village' => 'Tashithang', 'mas_gewog_id' => 18, 'created_by' => 1],
            ['id' => 238, 'village' => 'Baleggang', 'mas_gewog_id' => 19, 'created_by' => 1],
            ['id' => 239, 'village' => 'Dogaag', 'mas_gewog_id' => 19, 'created_by' => 1],
            ['id' => 240, 'village' => 'Gozhi', 'mas_gewog_id' => 19, 'created_by' => 1],
            ['id' => 241, 'village' => 'Gozhi Maed', 'mas_gewog_id' => 19, 'created_by' => 1],
            ['id' => 242, 'village' => 'Gozhi Toed', 'mas_gewog_id' => 19, 'created_by' => 1],
            ['id' => 243, 'village' => 'Kanakha', 'mas_gewog_id' => 20, 'created_by' => 1],
            ['id' => 244, 'village' => 'Lhaling', 'mas_gewog_id' => 20, 'created_by' => 1],
            ['id' => 245, 'village' => 'Nyindukha', 'mas_gewog_id' => 20, 'created_by' => 1],
            ['id' => 246, 'village' => 'Tanabji', 'mas_gewog_id' => 20, 'created_by' => 1],
            ['id' => 247, 'village' => 'Pungzhi', 'mas_gewog_id' => 20, 'created_by' => 1],
            ['id' => 248, 'village' => 'Dalithang', 'mas_gewog_id' => 20, 'created_by' => 1],
            ['id' => 249, 'village' => 'Gangjab', 'mas_gewog_id' => 20, 'created_by' => 1],
            ['id' => 250, 'village' => 'Khagochen', 'mas_gewog_id' => 20, 'created_by' => 1],
            ['id' => 251, 'village' => 'Aetosi', 'mas_gewog_id' => 20, 'created_by' => 1],
            ['id' => 252, 'village' => 'Bartsha', 'mas_gewog_id' => 20, 'created_by' => 1],
            ['id' => 253, 'village' => 'Buchunang', 'mas_gewog_id' => 20, 'created_by' => 1],
            ['id' => 254, 'village' => 'Namgaylang', 'mas_gewog_id' => 20, 'created_by' => 1],
            ['id' => 255, 'village' => 'Jurugang', 'mas_gewog_id' => 20, 'created_by' => 1],
            ['id' => 256, 'village' => 'Kazhithang', 'mas_gewog_id' => 20, 'created_by' => 1],
            ['id' => 257, 'village' => 'Lungtengang', 'mas_gewog_id' => 20, 'created_by' => 1],
            ['id' => 258, 'village' => 'Karmaling (Kerabari)', 'mas_gewog_id' => 21, 'created_by' => 1],
            ['id' => 259, 'village' => 'Omchhu (Homa)', 'mas_gewog_id' => 21, 'created_by' => 1],
            ['id' => 260, 'village' => 'Labtsakha (Deorali)', 'mas_gewog_id' => 21, 'created_by' => 1],
            ['id' => 261, 'village' => 'Senchumthang (Dalbari)', 'mas_gewog_id' => 21, 'created_by' => 1],
            ['id' => 262, 'village' => 'Ganglingna (Labrang)', 'mas_gewog_id' => 21, 'created_by' => 1],
            ['id' => 263, 'village' => 'Jemthang (Balabas)', 'mas_gewog_id' => 21, 'created_by' => 1],
            ['id' => 264, 'village' => 'Pogtog', 'mas_gewog_id' => 22, 'created_by' => 1],
            ['id' => 265, 'village' => 'Gumla', 'mas_gewog_id' => 22, 'created_by' => 1],
            ['id' => 266, 'village' => 'Pasger (Paksey)', 'mas_gewog_id' => 22, 'created_by' => 1],
            ['id' => 267, 'village' => 'Akhochen', 'mas_gewog_id' => 22, 'created_by' => 1],
            ['id' => 268, 'village' => 'Thomgang', 'mas_gewog_id' => 22, 'created_by' => 1],
            ['id' => 269, 'village' => 'Gibsa', 'mas_gewog_id' => 22, 'created_by' => 1],
            ['id' => 270, 'village' => 'Baloong', 'mas_gewog_id' => 23, 'created_by' => 1],
            ['id' => 271, 'village' => 'Thasa', 'mas_gewog_id' => 23, 'created_by' => 1],
            ['id' => 272, 'village' => 'Kompa', 'mas_gewog_id' => 23, 'created_by' => 1],
            ['id' => 273, 'village' => 'Barna', 'mas_gewog_id' => 23, 'created_by' => 1],
            ['id' => 274, 'village' => 'Sidpa', 'mas_gewog_id' => 23, 'created_by' => 1],
            ['id' => 275, 'village' => 'Majathang (Lamchey)', 'mas_gewog_id' => 24, 'created_by' => 1],
            ['id' => 276, 'village' => 'Tshaemjeena', 'mas_gewog_id' => 24, 'created_by' => 1],
            ['id' => 277, 'village' => 'Tshaemzhi Gosa (Tshaemjeena/Devitar)', 'mas_gewog_id' => 24, 'created_by' => 1],
            ['id' => 278, 'village' => 'Chongsamling (Sibsooni)', 'mas_gewog_id' => 24, 'created_by' => 1],
            ['id' => 279, 'village' => 'Lhamoidzingkha (Kalikhola)', 'mas_gewog_id' => 24, 'created_by' => 1],
            ['id' => 280, 'village' => 'Loongsilsa (Daragaon)', 'mas_gewog_id' => 24, 'created_by' => 1],
            ['id' => 281, 'village' => 'Kuendrelthang (Majigaon)', 'mas_gewog_id' => 24, 'created_by' => 1],
            ['id' => 282, 'village' => 'Dramze Kesa (Katarey)', 'mas_gewog_id' => 25, 'created_by' => 1],
            ['id' => 283, 'village' => 'Tsheluthang (Suntoley)', 'mas_gewog_id' => 25, 'created_by' => 1],
            ['id' => 284, 'village' => 'Yarpheling (Solmoley)', 'mas_gewog_id' => 25, 'created_by' => 1],
            ['id' => 285, 'village' => 'Nyeltshosa (Basiney)', 'mas_gewog_id' => 25, 'created_by' => 1],
            ['id' => 286, 'village' => 'Lakpaling (Manglabarey)', 'mas_gewog_id' => 25, 'created_by' => 1],
            ['id' => 287, 'village' => 'Nichula', 'mas_gewog_id' => 25, 'created_by' => 1],
            ['id' => 288, 'village' => 'Damchhunang (Allay)', 'mas_gewog_id' => 25, 'created_by' => 1],
            ['id' => 289, 'village' => 'Dangreyboog (Bichgoan)', 'mas_gewog_id' => 25, 'created_by' => 1],
            ['id' => 290, 'village' => 'Omchhugang (Apgachi)', 'mas_gewog_id' => 25, 'created_by' => 1],
            ['id' => 291, 'village' => 'Gangtokha (Daragoan)', 'mas_gewog_id' => 25, 'created_by' => 1],
            ['id' => 292, 'village' => 'Shamdolay', 'mas_gewog_id' => 26, 'created_by' => 1],
            ['id' => 293, 'village' => 'Tashiding', 'mas_gewog_id' => 26, 'created_by' => 1],
            ['id' => 294, 'village' => 'Namchagla', 'mas_gewog_id' => 26, 'created_by' => 1],
            ['id' => 295, 'village' => 'Norbuling (Lodoma)', 'mas_gewog_id' => 26, 'created_by' => 1],
            ['id' => 296, 'village' => 'Langchhenthang (Hathikhara)', 'mas_gewog_id' => 26, 'created_by' => 1],
            ['id' => 297, 'village' => 'Gangyab (Gopeni)', 'mas_gewog_id' => 26, 'created_by' => 1],
            ['id' => 298, 'village' => 'Gelegchhu', 'mas_gewog_id' => 27, 'created_by' => 1],
            ['id' => 299, 'village' => 'Salambi', 'mas_gewog_id' => 27, 'created_by' => 1],
            ['id' => 300, 'village' => 'Gakidthang', 'mas_gewog_id' => 27, 'created_by' => 1],
            ['id' => 301, 'village' => 'Tsangkha', 'mas_gewog_id' => 27, 'created_by' => 1],
            ['id' => 302, 'village' => 'Rongchhu (Bandarchu)', 'mas_gewog_id' => 27, 'created_by' => 1],
            ['id' => 303, 'village' => 'Zinchila', 'mas_gewog_id' => 27, 'created_by' => 1],
            ['id' => 304, 'village' => 'Satshamchhu (Budheychu)', 'mas_gewog_id' => 27, 'created_by' => 1],
            ['id' => 305, 'village' => 'Goongpa Soomchu (Tisgharay)', 'mas_gewog_id' => 27, 'created_by' => 1],
            ['id' => 306, 'village' => 'Pateykha', 'mas_gewog_id' => 27, 'created_by' => 1],
            ['id' => 307, 'village' => 'Babythang', 'mas_gewog_id' => 27, 'created_by' => 1],
            ['id' => 308, 'village' => 'Tsendagang', 'mas_gewog_id' => 28, 'created_by' => 1],
            ['id' => 309, 'village' => 'Tsendagang (Suntoley)', 'mas_gewog_id' => 28, 'created_by' => 1],
            ['id' => 310, 'village' => 'Gangzur', 'mas_gewog_id' => 28, 'created_by' => 1],
            ['id' => 311, 'village' => 'Gangzur Maed (Salaree)', 'mas_gewog_id' => 28, 'created_by' => 1],
            ['id' => 312, 'village' => 'Gangzur (Shamdolay)', 'mas_gewog_id' => 28, 'created_by' => 1],
            ['id' => 313, 'village' => 'Gangzur (Panakhola)', 'mas_gewog_id' => 28, 'created_by' => 1],
            ['id' => 314, 'village' => 'Gangzur Toed (Pasebung)', 'mas_gewog_id' => 28, 'created_by' => 1],
            ['id' => 315, 'village' => 'Dharay', 'mas_gewog_id' => 28, 'created_by' => 1],
            ['id' => 316, 'village' => 'Yuebug (Majuwa)', 'mas_gewog_id' => 28, 'created_by' => 1],
            ['id' => 317, 'village' => 'Norbuzhingkha', 'mas_gewog_id' => 28, 'created_by' => 1],
            ['id' => 318, 'village' => 'Norbuzhingkha (Panakhola)', 'mas_gewog_id' => 28, 'created_by' => 1],
            ['id' => 319, 'village' => 'Samarchu (Samakhola)', 'mas_gewog_id' => 28, 'created_by' => 1],
            ['id' => 320, 'village' => 'Pelling', 'mas_gewog_id' => 29, 'created_by' => 1],
            ['id' => 321, 'village' => 'Tongshong (Tongzho)', 'mas_gewog_id' => 29, 'created_by' => 1],
            ['id' => 322, 'village' => 'Jangsagang', 'mas_gewog_id' => 29, 'created_by' => 1],
            ['id' => 323, 'village' => 'Tashigang', 'mas_gewog_id' => 29, 'created_by' => 1],
            ['id' => 324, 'village' => 'Samaed', 'mas_gewog_id' => 29, 'created_by' => 1],
            ['id' => 325, 'village' => 'Karlingzingkha', 'mas_gewog_id' => 29, 'created_by' => 1],
            ['id' => 326, 'village' => 'Tsangleykha', 'mas_gewog_id' => 29, 'created_by' => 1],
            ['id' => 327, 'village' => 'Zamtog', 'mas_gewog_id' => 29, 'created_by' => 1],
            ['id' => 328, 'village' => 'Gayza', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 329, 'village' => 'Zomina', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 330, 'village' => 'Tomu', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 331, 'village' => 'Jabisa', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 332, 'village' => 'Chubdey', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 333, 'village' => 'Bara', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 334, 'village' => 'Chruawog', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 335, 'village' => 'Damjee', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 336, 'village' => 'Tsanakha', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 337, 'village' => 'Potogang', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 338, 'village' => 'Chasungsa', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 339, 'village' => 'Churaphakha', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 340, 'village' => 'Jizhi', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 341, 'village' => 'Selikha', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 342, 'village' => 'Barsha', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 343, 'village' => 'Yeomena', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 344, 'village' => 'Bayzhina', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 345, 'village' => 'Chalakha', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 346, 'village' => 'Kabina', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 347, 'village' => 'Zhazhukha', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 348, 'village' => 'Namphakha', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 349, 'village' => 'Jazhidingkha', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 350, 'village' => 'Yeodo', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 351, 'village' => 'Khailog', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 352, 'village' => 'Tashithang', 'mas_gewog_id' => 30, 'created_by' => 1],
            ['id' => 353, 'village' => 'Chhogley', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 354, 'village' => 'Gathana', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 355, 'village' => 'Khailog', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 356, 'village' => 'Phulakha', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 357, 'village' => 'Mani', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 358, 'village' => 'Dongyebi', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 359, 'village' => 'Tabchen', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 360, 'village' => 'Yemena', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 361, 'village' => 'Baychhu', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 362, 'village' => 'Tsebgang', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 363, 'village' => 'Tsheringkha', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 364, 'village' => 'Datakha', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 365, 'village' => 'Zamna', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 366, 'village' => 'Zanang', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 367, 'village' => 'Thangkha', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 368, 'village' => 'Lungchukha', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 369, 'village' => 'Neukha', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 370, 'village' => 'Womchugang', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 371, 'village' => 'Dochong', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 372, 'village' => 'Belpakha', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 373, 'village' => 'Tsangkha', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 374, 'village' => 'Amochhu', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 375, 'village' => 'Nurbi', 'mas_gewog_id' => 31, 'created_by' => 1],
            ['id' => 376, 'village' => 'Gayza', 'mas_gewog_id' => 32, 'created_by' => 1],
            ['id' => 377, 'village' => 'Lungo', 'mas_gewog_id' => 32, 'created_by' => 1],
            ['id' => 378, 'village' => 'Chongra', 'mas_gewog_id' => 32, 'created_by' => 1],
            ['id' => 379, 'village' => 'Lubcha', 'mas_gewog_id' => 32, 'created_by' => 1],
            ['id' => 380, 'village' => 'Neylug', 'mas_gewog_id' => 32, 'created_by' => 1],
            ['id' => 381, 'village' => 'Pazhi', 'mas_gewog_id' => 32, 'created_by' => 1],
            ['id' => 382, 'village' => 'Toedkor', 'mas_gewog_id' => 32, 'created_by' => 1],
            ['id' => 383, 'village' => 'Raminang', 'mas_gewog_id' => 33, 'created_by' => 1],
            ['id' => 384, 'village' => 'Uesana', 'mas_gewog_id' => 33, 'created_by' => 1],
            ['id' => 385, 'village' => 'Drangsho', 'mas_gewog_id' => 33, 'created_by' => 1],
            ['id' => 386, 'village' => 'Wachey', 'mas_gewog_id' => 33, 'created_by' => 1],
            ['id' => 387, 'village' => 'Relo', 'mas_gewog_id' => 33, 'created_by' => 1],
            ['id' => 388, 'village' => 'Shangsa', 'mas_gewog_id' => 33, 'created_by' => 1],
            ['id' => 389, 'village' => 'Tagshor', 'mas_gewog_id' => 33, 'created_by' => 1],
            ['id' => 390, 'village' => 'Threlga', 'mas_gewog_id' => 33, 'created_by' => 1],
            ['id' => 391, 'village' => 'Lhedi', 'mas_gewog_id' => 33, 'created_by' => 1],
            ['id' => 392, 'village' => 'Tshozhi', 'mas_gewog_id' => 33, 'created_by' => 1],
            ['id' => 393, 'village' => 'Dotag', 'mas_gewog_id' => 33, 'created_by' => 1],
            ['id' => 394, 'village' => 'Thangza', 'mas_gewog_id' => 33, 'created_by' => 1],
            ['id' => 395, 'village' => 'Toenchoe', 'mas_gewog_id' => 33, 'created_by' => 1],
            ['id' => 396, 'village' => 'Choomgpa', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 397, 'village' => 'Jamgoen', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 398, 'village' => 'Yetshephu', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 399, 'village' => 'Gyensa', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 400, 'village' => 'Tokey', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 401, 'village' => 'Chenpa', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 402, 'village' => 'Geychhukha', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 403, 'village' => 'Machina', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 404, 'village' => 'Takchugoenpa', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 405, 'village' => 'Tsenka', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 406, 'village' => 'Tsenkagoenpa', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 407, 'village' => 'Chubarna', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 408, 'village' => 'Dongsana/Taloong', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 409, 'village' => 'Gungkha', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 410, 'village' => 'Longlong', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 411, 'village' => 'Makana', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 412, 'village' => 'Pangphu', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 413, 'village' => 'Wooka', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 414, 'village' => 'Yulang', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 415, 'village' => 'Yangoen', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 416, 'village' => 'Yangthang', 'mas_gewog_id' => 34, 'created_by' => 1],
            ['id' => 417, 'village' => 'Dorithasa', 'mas_gewog_id' => 35, 'created_by' => 1],
            ['id' => 418, 'village' => 'Yangtse', 'mas_gewog_id' => 35, 'created_by' => 1],
            ['id' => 419, 'village' => 'Kowkha', 'mas_gewog_id' => 35, 'created_by' => 1],
            ['id' => 420, 'village' => 'Ta-nga/Chigo', 'mas_gewog_id' => 35, 'created_by' => 1],
            ['id' => 421, 'village' => 'Rangtse', 'mas_gewog_id' => 35, 'created_by' => 1],
            ['id' => 422, 'village' => 'Yokha', 'mas_gewog_id' => 35, 'created_by' => 1],
            ['id' => 423, 'village' => 'Thangdokha', 'mas_gewog_id' => 35, 'created_by' => 1],
            ['id' => 424, 'village' => 'Saidzong', 'mas_gewog_id' => 35, 'created_by' => 1],
            ['id' => 425, 'village' => 'Gangrinmo', 'mas_gewog_id' => 35, 'created_by' => 1],
            ['id' => 426, 'village' => 'Ngatse', 'mas_gewog_id' => 35, 'created_by' => 1],
            ['id' => 427, 'village' => 'Phootsena', 'mas_gewog_id' => 35, 'created_by' => 1],
            ['id' => 428, 'village' => 'Fetena', 'mas_gewog_id' => 35, 'created_by' => 1],
            ['id' => 429, 'village' => 'Sertena', 'mas_gewog_id' => 35, 'created_by' => 1],
            ['id' => 430, 'village' => 'Bali', 'mas_gewog_id' => 36, 'created_by' => 1],
            ['id' => 431, 'village' => 'Mombitshokha', 'mas_gewog_id' => 36, 'created_by' => 1],
            ['id' => 432, 'village' => 'Kargoen', 'mas_gewog_id' => 36, 'created_by' => 1],
            ['id' => 433, 'village' => 'Hatam', 'mas_gewog_id' => 36, 'created_by' => 1],
            ['id' => 434, 'village' => 'Dragding', 'mas_gewog_id' => 36, 'created_by' => 1],
            ['id' => 435, 'village' => 'Karjena', 'mas_gewog_id' => 36, 'created_by' => 1],
            ['id' => 436, 'village' => 'Gargkha', 'mas_gewog_id' => 36, 'created_by' => 1],
            ['id' => 437, 'village' => 'Naktshang', 'mas_gewog_id' => 36, 'created_by' => 1],
            ['id' => 438, 'village' => 'Namdhu', 'mas_gewog_id' => 36, 'created_by' => 1],
            ['id' => 439, 'village' => 'Ingo', 'mas_gewog_id' => 36, 'created_by' => 1],
            ['id' => 440, 'village' => 'Pharikha', 'mas_gewog_id' => 36, 'created_by' => 1],
            ['id' => 441, 'village' => 'Wangtsa', 'mas_gewog_id' => 36, 'created_by' => 1],
            ['id' => 442, 'village' => 'Dorikha', 'mas_gewog_id' => 37, 'created_by' => 1],
            ['id' => 443, 'village' => 'Kouna', 'mas_gewog_id' => 37, 'created_by' => 1],
            ['id' => 444, 'village' => 'Langjogang', 'mas_gewog_id' => 37, 'created_by' => 1],
            ['id' => 445, 'village' => 'Phendona', 'mas_gewog_id' => 37, 'created_by' => 1],
            ['id' => 446, 'village' => 'Barakha', 'mas_gewog_id' => 37, 'created_by' => 1],
            ['id' => 447, 'village' => 'Barasham', 'mas_gewog_id' => 37, 'created_by' => 1],
            ['id' => 448, 'village' => 'Chumeyding', 'mas_gewog_id' => 37, 'created_by' => 1],
            ['id' => 449, 'village' => 'Langpa', 'mas_gewog_id' => 37, 'created_by' => 1],
            ['id' => 450, 'village' => 'Lhakhangchen', 'mas_gewog_id' => 37, 'created_by' => 1],
            ['id' => 451, 'village' => 'Norbugang', 'mas_gewog_id' => 37, 'created_by' => 1],
            ['id' => 452, 'village' => 'Balamnang', 'mas_gewog_id' => 37, 'created_by' => 1],
            ['id' => 453, 'village' => 'Jenkanang', 'mas_gewog_id' => 37, 'created_by' => 1],
            ['id' => 454, 'village' => 'Pudunang', 'mas_gewog_id' => 37, 'created_by' => 1],
            ['id' => 455, 'village' => 'Sharri', 'mas_gewog_id' => 37, 'created_by' => 1],
            ['id' => 456, 'village' => 'Bibi', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 457, 'village' => 'Dongtse', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 458, 'village' => 'Mochhu', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 459, 'village' => 'Nakha', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 460, 'village' => 'Nakhatshochen', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 461, 'village' => 'Tingma', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 462, 'village' => 'Tashigang', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 463, 'village' => 'Shaba', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 464, 'village' => 'Shepji', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 465, 'village' => 'Chinga', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 466, 'village' => 'Shema', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 467, 'village' => 'Yaba', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 468, 'village' => 'Ama', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 469, 'village' => 'Tsanglingna', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 470, 'village' => 'Gyeldrakha', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 471, 'village' => 'Nakhekha', 'mas_gewog_id' => 38, 'created_by' => 1],
            ['id' => 472, 'village' => 'Betso', 'mas_gewog_id' => 39, 'created_by' => 1],
            ['id' => 473, 'village' => 'Doomchhog', 'mas_gewog_id' => 39, 'created_by' => 1],
            ['id' => 474, 'village' => 'Geyruna', 'mas_gewog_id' => 39, 'created_by' => 1],
            ['id' => 475, 'village' => 'Karnag', 'mas_gewog_id' => 39, 'created_by' => 1],
            ['id' => 476, 'village' => 'Pagekha', 'mas_gewog_id' => 39, 'created_by' => 1],
            ['id' => 477, 'village' => 'Sangkiri', 'mas_gewog_id' => 39, 'created_by' => 1],
            ['id' => 478, 'village' => 'Bangyena', 'mas_gewog_id' => 39, 'created_by' => 1],
            ['id' => 479, 'village' => 'Dranggoen', 'mas_gewog_id' => 39, 'created_by' => 1],
            ['id' => 480, 'village' => 'Kipri', 'mas_gewog_id' => 39, 'created_by' => 1],
            ['id' => 481, 'village' => 'Tagchhu', 'mas_gewog_id' => 39, 'created_by' => 1],
            ['id' => 482, 'village' => 'Takchugoenpa', 'mas_gewog_id' => 39, 'created_by' => 1],
            ['id' => 483, 'village' => 'Goensakha', 'mas_gewog_id' => 39, 'created_by' => 1],
            ['id' => 484, 'village' => 'Hagoenpa', 'mas_gewog_id' => 39, 'created_by' => 1],
            ['id' => 485, 'village' => 'Tsiloongkha', 'mas_gewog_id' => 39, 'created_by' => 1],
            ['id' => 486, 'village' => 'Tshaphel', 'mas_gewog_id' => 39, 'created_by' => 1],
            ['id' => 487, 'village' => 'Ney', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 488, 'village' => 'Lingabi', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 489, 'village' => 'Magar', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 490, 'village' => 'Kyidloong', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 491, 'village' => 'Changray', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 492, 'village' => 'Samling', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 493, 'village' => 'Khamphu', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 494, 'village' => 'Lekpa', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 495, 'village' => 'Rotpa', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 496, 'village' => 'Shomshing', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 497, 'village' => 'Tsholing', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 498, 'village' => 'Thrima', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 499, 'village' => 'Zhamling', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 500, 'village' => 'Shawa', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 501, 'village' => 'Khaujoong', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 502, 'village' => 'Youngmaling', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 503, 'village' => 'Namseygang', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 504, 'village' => 'Sapho', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 505, 'village' => 'Amchi', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 506, 'village' => 'Chhesa', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 507, 'village' => 'Jalamzur', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 508, 'village' => 'Nyimzhong', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 509, 'village' => 'Tangsa', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 510, 'village' => 'Taushing', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 511, 'village' => 'Taushinggoenpa', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 512, 'village' => 'Tongling', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 513, 'village' => 'Thimyul', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 514, 'village' => 'Dhuthay', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 515, 'village' => 'Jang', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 516, 'village' => 'Napzala', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 517, 'village' => 'Phatala', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 518, 'village' => 'Tagzibar', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 519, 'village' => 'Denkaling', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 520, 'village' => 'Gangzur', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 521, 'village' => 'Ngar/Nyar', 'mas_gewog_id' => 40, 'created_by' => 1],
            ['id' => 522, 'village' => 'Rolmateng', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 523, 'village' => 'Tsang-ngo', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 524, 'village' => 'Khoema', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 525, 'village' => 'Khoma', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 526, 'village' => 'Lukchu', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 527, 'village' => 'Berpa', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 528, 'village' => 'Pengtse', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 529, 'village' => 'Nyalamdung', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 530, 'village' => 'Babtong', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 531, 'village' => 'Dragteng', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 532, 'village' => 'Kemtshong', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 533, 'village' => 'Goenkhar', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 534, 'village' => 'Karphu', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 535, 'village' => 'Laber', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 536, 'village' => 'Gangla', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 537, 'village' => 'Lawa', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 538, 'village' => 'Serphu', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 539, 'village' => 'Taya', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 540, 'village' => 'Kholma', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 541, 'village' => 'Pangkhar', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 542, 'village' => 'Zangkhar', 'mas_gewog_id' => 41, 'created_by' => 1],
            ['id' => 543, 'village' => 'Yumchhe', 'mas_gewog_id' => 42, 'created_by' => 1],
            ['id' => 544, 'village' => 'Kharchung/Pam', 'mas_gewog_id' => 42, 'created_by' => 1],
            ['id' => 545, 'village' => 'Ladrong', 'mas_gewog_id' => 42, 'created_by' => 1],
            ['id' => 546, 'village' => 'Ngang Ngae', 'mas_gewog_id' => 42, 'created_by' => 1],
            ['id' => 547, 'village' => 'Jarey', 'mas_gewog_id' => 42, 'created_by' => 1],
            ['id' => 548, 'village' => 'Trapashing', 'mas_gewog_id' => 42, 'created_by' => 1],
            ['id' => 549, 'village' => 'Changkhala', 'mas_gewog_id' => 42, 'created_by' => 1],
            ['id' => 550, 'village' => 'Wayang', 'mas_gewog_id' => 42, 'created_by' => 1],
            ['id' => 551, 'village' => 'Yabi', 'mas_gewog_id' => 42, 'created_by' => 1],
            ['id' => 552, 'village' => 'Jasabi', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 553, 'village' => 'Tergang', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 554, 'village' => 'Uygenphoog', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 555, 'village' => 'Chagdzom', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 556, 'village' => 'Chhusa', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 557, 'village' => 'Drabling', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 558, 'village' => 'Gurta', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 559, 'village' => 'Nagling', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 560, 'village' => 'Pirbee', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 561, 'village' => 'Shangthongling', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 562, 'village' => 'Thangbi', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 563, 'village' => 'Wamdrang', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 564, 'village' => 'Garong', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 565, 'village' => 'Goshingpang', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 566, 'village' => 'Ruling', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 567, 'village' => 'Sershong', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 568, 'village' => 'Maenbi', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 569, 'village' => 'Nyaray', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 570, 'village' => 'Shauzhong', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 571, 'village' => 'Churchuma', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 572, 'village' => 'Signar', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 573, 'village' => 'Wawel', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 574, 'village' => 'Taling', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 575, 'village' => 'Tangroong', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 576, 'village' => 'Thuenpey', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 577, 'village' => 'Zongsar', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 578, 'village' => 'Arjhaling', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 579, 'village' => 'Chongsa', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 580, 'village' => 'Chhanyalgang', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 581, 'village' => 'Darjaygang', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 582, 'village' => 'Dongmaed', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 583, 'village' => 'Dungkar', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 584, 'village' => 'Jangtse', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 585, 'village' => 'Lamsaykapa', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 586, 'village' => 'Sugpee', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 587, 'village' => 'Tongmay', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 588, 'village' => 'Takharme', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 589, 'village' => 'Zimpong', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 590, 'village' => 'Chaktamin', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 591, 'village' => 'Lamsabi', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 592, 'village' => 'Serphu', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 593, 'village' => 'Sewel', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 594, 'village' => 'Sumdhang', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 595, 'village' => 'Thongjaling', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 596, 'village' => 'Thowa', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 597, 'village' => 'Tabi', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 598, 'village' => 'Tagdzong', 'mas_gewog_id' => 43, 'created_by' => 1],
            ['id' => 599, 'village' => 'Chalibi', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 600, 'village' => 'Dangsangoenpa', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 601, 'village' => 'Dungkardowa', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 602, 'village' => 'Gangkhar', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 603, 'village' => 'Garapho', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 604, 'village' => 'Kharsa', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 605, 'village' => 'Namdang', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 606, 'village' => 'Nyaibi', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 607, 'village' => 'Pelrigoenpa', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 608, 'village' => 'Samcheling', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 609, 'village' => 'Samling', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 610, 'village' => 'Shangrabi', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 611, 'village' => 'Shormaed', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 612, 'village' => 'Tungkhar', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 613, 'village' => 'Youngrab', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 614, 'village' => 'Zhungkhar', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 615, 'village' => 'Dangling', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 616, 'village' => 'Khochen', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 617, 'village' => 'Maenjabi', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 618, 'village' => 'Sershingbi', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 619, 'village' => 'Yanglagoenpa', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 620, 'village' => 'Rawabi', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 621, 'village' => 'Rawabi Goenpa', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 622, 'village' => 'Yomaed', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 623, 'village' => 'Tagmochhu', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 624, 'village' => 'Youngshingphel', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 625, 'village' => 'Boushong', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 626, 'village' => 'Bamendrangsa', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 627, 'village' => 'Gorgan', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 628, 'village' => 'Takayla', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 629, 'village' => 'Bariphu', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 630, 'village' => 'Chengaling', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 631, 'village' => 'Dromzhong', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 632, 'village' => 'Gamshing', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 633, 'village' => 'Kasithang', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 634, 'village' => 'Langphog', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 635, 'village' => 'Oumzor', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 636, 'village' => 'Ledong', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 637, 'village' => 'Lekpagang', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 638, 'village' => 'Manigang', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 639, 'village' => 'Nadrang', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 640, 'village' => 'Ngamaling', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 641, 'village' => 'Tangpa', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 642, 'village' => 'Phagidroong', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 643, 'village' => 'Dosagang', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 644, 'village' => 'Kamdhar', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 645, 'village' => 'Katog', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 646, 'village' => 'Khampaling', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 647, 'village' => 'Khashaling', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 648, 'village' => 'Kimphay', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 649, 'village' => 'Kusumphay', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 650, 'village' => 'Larjab', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 651, 'village' => 'Lugarpang', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 652, 'village' => 'Moormo', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 653, 'village' => 'Namnangbi', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 654, 'village' => 'Pangsar', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 655, 'village' => 'Petsizor', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 656, 'village' => 'Phungshingang', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 657, 'village' => 'Rewaling', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 658, 'village' => 'Tashiling', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 659, 'village' => 'Thekcholing', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 660, 'village' => 'Thongjaling', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 661, 'village' => 'Tongmakhar', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 662, 'village' => 'Tsampdemo', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 663, 'village' => 'Zarthang', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 664, 'village' => 'Bumpashing', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 665, 'village' => 'Zarthang Goenpa', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 666, 'village' => 'Zungphu', 'mas_gewog_id' => 44, 'created_by' => 1],
            ['id' => 667, 'village' => 'Oonggar', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 668, 'village' => 'Zhongmaed', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 669, 'village' => 'Bamdhir', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 670, 'village' => 'Yurung', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 671, 'village' => 'Tshochen', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 672, 'village' => 'Balam', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 673, 'village' => 'Balam/Nimalawa', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 674, 'village' => 'Changchen', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 675, 'village' => 'Changshinpokpa', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 676, 'village' => 'Thangthrom Maed', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 677, 'village' => 'Thangthrom Maed Goenpa', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 678, 'village' => 'Drukla', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 679, 'village' => 'Dulebi', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 680, 'village' => 'Gongdar', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 681, 'village' => 'Gortshom', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 682, 'village' => 'Gulipang', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 683, 'village' => 'Janakchen', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 684, 'village' => 'Kermademo', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 685, 'village' => 'Khenye Lhakhang', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 686, 'village' => 'Lhakhangtshawa', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 687, 'village' => 'Mangdhir', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 688, 'village' => 'Mukpakhar', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 689, 'village' => 'Samdang', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 690, 'village' => 'Serbuchuka', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 691, 'village' => 'Singyebi', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 692, 'village' => 'Tachung', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 693, 'village' => 'Tonzibi', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 694, 'village' => 'Yamalung Goenpa', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 695, 'village' => 'Tshodrang', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 696, 'village' => 'Waney', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 697, 'village' => 'Yozer Goenpa', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 698, 'village' => 'Yokpaling', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 699, 'village' => 'Tongthrong', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 700, 'village' => 'Dowaletang', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 701, 'village' => 'Pangshingmey', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 702, 'village' => 'Obi', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 703, 'village' => 'Pholadowa', 'mas_gewog_id' => 45, 'created_by' => 1],
            ['id' => 704, 'village' => 'Amdrangchhu', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 705, 'village' => 'Chengling', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 706, 'village' => 'Zham', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 707, 'village' => 'Chusa', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 708, 'village' => 'Draledowa', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 709, 'village' => 'Legpachu', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 710, 'village' => 'Legchugang', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 711, 'village' => 'Legshogang', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 712, 'village' => 'Pumogang', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 713, 'village' => 'Dhokpabi', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 714, 'village' => 'Draag-gong', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 715, 'village' => 'Draag-gong Goenpa', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 716, 'village' => 'Jabum', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 717, 'village' => 'Jalang', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 718, 'village' => 'Keroo', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 719, 'village' => 'Phangchenbi', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 720, 'village' => 'Boo-dur', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 721, 'village' => 'Kupi-nyalsa', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 722, 'village' => 'Minjey', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 723, 'village' => 'Nyaka', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 724, 'village' => 'Sershing', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 725, 'village' => 'Tongling', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 726, 'village' => 'Wangzhing', 'mas_gewog_id' => 46, 'created_by' => 1],
            ['id' => 727, 'village' => 'Wambur', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 728, 'village' => 'Chim Gong', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 729, 'village' => 'Chungkha', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 730, 'village' => 'Dagarthang', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 731, 'village' => 'Jarkang', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 732, 'village' => 'Lagay', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 733, 'village' => 'Go-nyid', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 734, 'village' => 'Khablang', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 735, 'village' => 'Kiphung', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 736, 'village' => 'Sokarom', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 737, 'village' => 'Yanglong', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 738, 'village' => 'Domkhar', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 739, 'village' => 'Dongling', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 740, 'village' => 'Umling', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 741, 'village' => 'Bangtsho', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 742, 'village' => 'Barchhu', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 743, 'village' => 'Changmadung', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 744, 'village' => 'Chowa', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 745, 'village' => 'Dekaling', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 746, 'village' => 'Gamanang', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 747, 'village' => 'Godong/Gordong', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 748, 'village' => 'Kharphu', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 749, 'village' => 'Ngathung', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 750, 'village' => 'Phomed-doong', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 751, 'village' => 'Phowantay', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 752, 'village' => 'Phuntshochhoeling', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 753, 'village' => 'Phurshongang', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 754, 'village' => 'Sangphu', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 755, 'village' => 'Sokchen', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 756, 'village' => 'Takchu', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 757, 'village' => 'Tashi Ling', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 758, 'village' => 'Tongshi Lung', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 759, 'village' => 'Tongsheling', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 760, 'village' => 'Toekhar', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 761, 'village' => 'Tshangphu', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 762, 'village' => 'Tsochhen', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 763, 'village' => 'Genchungla', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 764, 'village' => 'Tsaenkhar', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 765, 'village' => 'Tsholadrang', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 766, 'village' => 'Autho', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 767, 'village' => 'Chulung', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 768, 'village' => 'Chharbi', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 769, 'village' => 'Changchang Goenpa', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 770, 'village' => 'Dongthrom', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 771, 'village' => 'Kawachen', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 772, 'village' => 'Langabi', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 773, 'village' => 'Lawsa', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 774, 'village' => 'Peldraphu', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 775, 'village' => 'Shermachhu', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 776, 'village' => 'Shermachhu Goenpa', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 777, 'village' => 'Trangka Shing', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 778, 'village' => 'Tshochim', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 779, 'village' => 'Tongphugang', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 780, 'village' => 'Guengdrang', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 781, 'village' => 'Yangla', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 782, 'village' => 'Artobadeb', 'mas_gewog_id' => 47, 'created_by' => 1],
            ['id' => 783, 'village' => 'Khebishing', 'mas_gewog_id' => 48, 'created_by' => 1],
            ['id' => 784, 'village' => 'Balam', 'mas_gewog_id' => 48, 'created_by' => 1],
            ['id' => 785, 'village' => 'Sangjuzor', 'mas_gewog_id' => 48, 'created_by' => 1],
            ['id' => 786, 'village' => 'Bahkaphai', 'mas_gewog_id' => 48, 'created_by' => 1],
            ['id' => 787, 'village' => 'Selkhar', 'mas_gewog_id' => 48, 'created_by' => 1],
            ['id' => 788, 'village' => 'Jadoong', 'mas_gewog_id' => 48, 'created_by' => 1],
            ['id' => 789, 'village' => 'Jadoong Goenpa', 'mas_gewog_id' => 48, 'created_by' => 1],
            ['id' => 790, 'village' => 'Jadoong Kha', 'mas_gewog_id' => 48, 'created_by' => 1],
            ['id' => 791, 'village' => 'Chhaling', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 792, 'village' => 'Toepaphu', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 793, 'village' => 'Bana', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 794, 'village' => 'Bolipang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 795, 'village' => 'Chaukileng', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 796, 'village' => 'Kharigab', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 797, 'village' => 'Kotshome', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 798, 'village' => 'Kurzam', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 799, 'village' => 'Lhakang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 800, 'village' => 'Lhakang Bana', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 801, 'village' => 'Lhakang Dongbar', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 802, 'village' => 'Lhakang Goenshing', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 803, 'village' => 'Lhakang Khoyur', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 804, 'village' => 'Lhakang Unakhang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 805, 'village' => 'Lhakang Lingchung', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 806, 'village' => 'Lhakang Pangjab', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 807, 'village' => 'Lhakang Ringseng', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 808, 'village' => 'Lhakang Ringseng', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 809, 'village' => 'Lhakang Sokpaling', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 810, 'village' => 'Lhakang Tengpa', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 811, 'village' => 'Namabi', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 812, 'village' => 'Nyerpa', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 813, 'village' => 'Salapho', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 814, 'village' => 'Shingkharzhong', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 815, 'village' => 'Sogpaling', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 816, 'village' => 'Tashipoktor', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 817, 'village' => 'Torzhonggor', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 818, 'village' => 'Wang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 819, 'village' => 'Zanglawang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 820, 'village' => 'Kharigab', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 821, 'village' => 'Pangjagpa', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 822, 'village' => 'Dopang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 823, 'village' => 'Bakhim', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 824, 'village' => 'Bameijangsa', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 825, 'village' => 'Chagsar', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 826, 'village' => 'Chulabi', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 827, 'village' => 'Kampasadong', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 828, 'village' => 'Pangthang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 829, 'village' => 'Namling', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 830, 'village' => 'Pogtor', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 831, 'village' => 'Rolmochhu', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 832, 'village' => 'Tagling', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 833, 'village' => 'Aagshaling', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 834, 'village' => 'Zhongje', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 835, 'village' => 'Dongtoed', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 836, 'village' => 'Dongtoed Bakhim', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 837, 'village' => 'Dopang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 838, 'village' => 'Japang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 839, 'village' => 'Khachorshing', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 840, 'village' => 'Khampaje', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 841, 'village' => 'Kharduma', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 842, 'village' => 'Khartong', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 843, 'village' => 'Kirzhong', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 844, 'village' => 'Masangkangjay', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 845, 'village' => 'Numabiwang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 846, 'village' => 'Tshangkhar', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 847, 'village' => 'Zhongkey', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 848, 'village' => 'Tagling', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 849, 'village' => 'Goensar', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 850, 'village' => 'Gortongla', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 851, 'village' => 'Budishing', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 852, 'village' => 'Remochhu', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 853, 'village' => 'Lungkang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 854, 'village' => 'Nagtshang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 855, 'village' => 'Nagtshangwog', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 856, 'village' => 'Oangthang Chungku', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 857, 'village' => 'Sapogtor', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 858, 'village' => 'Shebchi', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 859, 'village' => 'Thangthala', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 860, 'village' => 'Yangthang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 861, 'village' => 'Yoezer Pangthang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 862, 'village' => 'Aidurla', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 863, 'village' => 'Usdur', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 864, 'village' => 'Tshamkhang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 865, 'village' => 'Charzhong', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 866, 'village' => 'Domangla', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 867, 'village' => 'Gorsum', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 868, 'village' => 'Khoijongla', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 869, 'village' => 'Khoilajong', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 870, 'village' => 'Barigoila', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 871, 'village' => 'Pangthang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 872, 'village' => 'Thempang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 873, 'village' => 'Tshokila', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 874, 'village' => 'Jambi', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 875, 'village' => 'Barleng', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 876, 'village' => 'Bewling', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 877, 'village' => 'Chawasing', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 878, 'village' => 'Chewang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 879, 'village' => 'Damaling', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 880, 'village' => 'Darseng', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 881, 'village' => 'Nordangsa', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 882, 'village' => 'Pangthang Shokposeng', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 883, 'village' => 'Pemagayser', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 884, 'village' => 'Phodagnma', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 885, 'village' => 'Phumazur', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 886, 'village' => 'Rahambi', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 887, 'village' => 'Shogoseng', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 888, 'village' => 'Tikusalung', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 889, 'village' => 'Wangkhar', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 890, 'village' => 'Kadam', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 891, 'village' => 'Balingbi', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 892, 'village' => 'Changmashing', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 893, 'village' => 'Dokorbang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 894, 'village' => 'Dogtang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 895, 'village' => 'Dongjug', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 896, 'village' => 'Gensing', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 897, 'village' => 'Kamsa', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 898, 'village' => 'Kawakhoi', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 899, 'village' => 'Khemsang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 900, 'village' => 'Mentshang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 901, 'village' => 'Namathang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 902, 'village' => 'Pangthang', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 903, 'village' => 'Phachaphogchi', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 904, 'village' => 'Pangshing', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 905, 'village' => 'Sumthuen', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 906, 'village' => 'Tadzong', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 907, 'village' => 'Trashikhangsar', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 908, 'village' => 'Tshepadong', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 909, 'village' => 'Yoekhoi', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 910, 'village' => 'Yontenkhem', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 911, 'village' => 'Zhongje', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 912, 'village' => 'Zinthuen', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 913, 'village' => 'Jachuling', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 914, 'village' => 'Yoekhoi', 'mas_gewog_id' => 49, 'created_by' => 1],
            ['id' => 915, 'village' => 'Yangrapoongshing', 'mas_gewog_id' => 50, 'created_by' => 1],
            ['id' => 916, 'village' => 'Khamang', 'mas_gewog_id' => 50, 'created_by' => 1],
            ['id' => 917, 'village' => 'Doongshingma', 'mas_gewog_id' => 50, 'created_by' => 1],
            ['id' => 918, 'village' => 'Pam', 'mas_gewog_id' => 50, 'created_by' => 1],
            ['id' => 919, 'village' => 'Chagsakhar', 'mas_gewog_id' => 50, 'created_by' => 1],
            ['id' => 920, 'village' => 'Yetong', 'mas_gewog_id' => 50, 'created_by' => 1],
            ['id' => 921, 'village' => 'Bazor', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 922, 'village' => 'Laymey', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 923, 'village' => 'Laymey Serkhagphoog', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 924, 'village' => 'Serkhaphug', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 925, 'village' => 'Yengkhartshing', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 926, 'village' => 'Dramdetse', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 927, 'village' => 'Shaphangma', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 928, 'village' => 'Ongkhar', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 929, 'village' => 'Jiwa', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 930, 'village' => 'Luwang', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 931, 'village' => 'Ngarphai', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 932, 'village' => 'Phentshomo', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 933, 'village' => 'Ngarphel', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 934, 'village' => 'Shadang', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 935, 'village' => 'Gashari', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 936, 'village' => 'Zangkhar', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 937, 'village' => 'Gobka', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 938, 'village' => 'Bikhar', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 939, 'village' => 'Thramlo', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 940, 'village' => 'Thoongdabi', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 941, 'village' => 'Thoongdari', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 942, 'village' => 'Waichur', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 943, 'village' => 'Yalum', 'mas_gewog_id' => 51, 'created_by' => 1],
            ['id' => 944, 'village' => 'Drepoong', 'mas_gewog_id' => 52, 'created_by' => 1],
            ['id' => 945, 'village' => 'Labtsa Ka', 'mas_gewog_id' => 52, 'created_by' => 1],
            ['id' => 946, 'village' => 'Labtsa Kha', 'mas_gewog_id' => 52, 'created_by' => 1],
            ['id' => 947, 'village' => 'Chhagsuzor', 'mas_gewog_id' => 52, 'created_by' => 1],
            ['id' => 948, 'village' => 'Tsangkhar', 'mas_gewog_id' => 52, 'created_by' => 1],
            ['id' => 949, 'village' => 'Zunglen', 'mas_gewog_id' => 52, 'created_by' => 1],
            ['id' => 950, 'village' => 'Damkhar', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 951, 'village' => 'Dogmo', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 952, 'village' => 'Gorgdey', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 953, 'village' => 'Pangthang', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 954, 'village' => 'Phosala', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 955, 'village' => 'Salibi', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 956, 'village' => 'Salibi Dungda', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 957, 'village' => 'Toedkar', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 958, 'village' => 'Tshabor', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 959, 'village' => 'Weringla', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 960, 'village' => 'Bangbangla', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 961, 'village' => 'Chaibi', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 962, 'village' => 'Dekhar', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 963, 'village' => 'Dewabi', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 964, 'village' => 'Gorthongla', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 965, 'village' => 'Mantshang', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 966, 'village' => 'Miden', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 967, 'village' => 'Phadzong', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 968, 'village' => 'Bogarbi', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 969, 'village' => 'Daagsa', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 970, 'village' => 'Goenpa', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 971, 'village' => 'Gungdue', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 972, 'village' => 'Kumadzong', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 973, 'village' => 'Labtsa', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 974, 'village' => 'Phuchung Goenpa', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 975, 'village' => 'Tshambali', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 976, 'village' => 'Kormaed', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 977, 'village' => 'Pangtong', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 978, 'village' => 'Pikari', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 979, 'village' => 'Yangbari', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 980, 'village' => 'Baagla Edi', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 981, 'village' => 'Baagla', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 982, 'village' => 'Baagla Goenpa', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 983, 'village' => 'Baagla Khimong', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 984, 'village' => 'Dengkaling', 'mas_gewog_id' => 53, 'created_by' => 1],
            ['id' => 985, 'village' => 'Ngamphoog', 'mas_gewog_id' => 54, 'created_by' => 1],
            ['id' => 986, 'village' => 'Sangkama', 'mas_gewog_id' => 54, 'created_by' => 1],
            ['id' => 987, 'village' => 'Bilam', 'mas_gewog_id' => 54, 'created_by' => 1],
            ['id' => 988, 'village' => 'Aring Daza', 'mas_gewog_id' => 54, 'created_by' => 1],
            ['id' => 989, 'village' => 'Dangkila', 'mas_gewog_id' => 54, 'created_by' => 1],
            ['id' => 990, 'village' => 'Dumdey', 'mas_gewog_id' => 54, 'created_by' => 1],
            ['id' => 991, 'village' => 'Gongtshang', 'mas_gewog_id' => 54, 'created_by' => 1],
            ['id' => 992, 'village' => 'Korkhang', 'mas_gewog_id' => 54, 'created_by' => 1],
            ['id' => 993, 'village' => 'Maphai', 'mas_gewog_id' => 54, 'created_by' => 1],
            ['id' => 994, 'village' => 'Menchaphoog', 'mas_gewog_id' => 54, 'created_by' => 1],
            ['id' => 995, 'village' => 'Moodoongbi', 'mas_gewog_id' => 54, 'created_by' => 1],
            ['id' => 996, 'village' => 'Pegpela', 'mas_gewog_id' => 54, 'created_by' => 1],
            ['id' => 997, 'village' => 'Ngangri', 'mas_gewog_id' => 54, 'created_by' => 1],
            ['id' => 998, 'village' => 'Shingmung', 'mas_gewog_id' => 54, 'created_by' => 1],
            ['id' => 999, 'village' => 'Bacha', 'mas_gewog_id' => 54, 'created_by' => 1],
            ['id' => 1000, 'village' => 'Chenchari', 'mas_gewog_id' => 54, 'created_by' => 1]
        ]);
    }
}
