<style>
   .report-meta-block {
        margin-top: 20px;
        padding: 10px 0;
    }

    .report-meta-row {
        display: flex;
        flex-wrap: wrap; /* allows wrapping if needed */
        gap: 60px; /* spacing between items */
        align-items: center;
        font-size: 1em;
    }

    .meta-item {
        display: flex;
        align-items: center;
        white-space: nowrap;
    }

    .meta-item .label {
        font-weight: bold;
        margin-right: 5px;
    }


</style>

<div class="report-meta-block">
    <div class="report-meta-row">
        <div class="meta-item">
            <span class="label">Generated On:</span>
            <span>{{ date('Y-m-d') }}</span>
        </div>

        <div class="meta-item">
            <span class="label">Generated By:</span>
            <span>{{ auth()->user()->username }}</span>
        </div>

        @if($fromDate)
        <div class="meta-item">
            <span class="label">Reporting Period:</span>
            <span>{{ $fromDate }} to {{ $toDate ?? date('Y-m-d') }}</span>
        </div>
        @endif
    </div>
</div>
